apiVersion: v1
kind: Service
metadata:
  name: admin-portal-service
spec:
  type: NodePort
  selector:
    app: admin-portal
  ports:
    - protocol: TCP
      port: 3007
      targetPort: 3007
      nodePort: 30008
