apiVersion: v1
kind: Service
metadata:
  name: aline-landing-portal-service
spec:
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30009
    protocol: TCP
    name: http
  selector:
    app: aline-landing-portal
