apiVersion: v1
kind: Service
metadata:
  name: landing-portal
  namespace: microservices-system  # Specify the namespace here
spec:
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    app: landing-portal
