apiVersion: v1
kind: Service
metadata:
  name: aline-account-microservice
spec:
  type: ClusterIP # Use NodePort or LoadBalancer if external access is needed
  ports:
  - port: 8074
    targetPort: 8074
  selector:
    app: aline-account-microservice
