apiVersion: v1
kind: Service
metadata:
  name: underwriter-service
  namespace: microservices-system  # Specify the namespace here
spec:
  type: ClusterIP
  ports:
  - port: 8071
    targetPort: 8071
  selector:
    app: aline-underwriter-microservice
