apiVersion: v1
kind: Service
metadata:
  name: admin-portal
  namespace: microservices-system  # Specify the namespace here
spec:
  type: NodePort
  ports:
  - port: 3007
    targetPort: 3007
  selector:
    app: aline-admin-portal
