apiVersion: v1
kind: Service
metadata:
  name: aline-account-microservice-service
spec:
  type: NodePort
  ports:
  - port: 8074
    targetPort: 8074
    nodePort: 30004
    protocol: TCP
    name: http
  selector:
    app: aline-account-microservice
